# travis.yml

services:
    - docker

before_install:
    - docker --version

install:
    - git clone https://github.com/docker-library/official-images.git official-images

# Assist with ci test debugging:
#   - DEBUG=1

before_script:
    - image="2stacks/nginx-lb"
    - docker build -t "$image" .
    - docker inspect "$image"
    - docker run --rm "$image" nginx -v

script:
    - official-images/test/run.sh "$image"
#   - test/run.sh "$image"

after_script:
    - docker images
